import { FILE_NAMES, URLS } from "./fileNames.js";

export const ALL_ASSETS = new Map();

export const TYPES: Record<string, string> = {
  IMAGE: "image",
  SOUND: "sound",
};

export const CHECKER: Record<string, string> = {
  png: TYPES.IMAGE,
  mp3: TYPES.SOUND,
  ogg: TYPES.SOUND,
};

// prettier-ignore
export const NAMES: string[][] = [
  //GUI
  [`${FILE_NAMES.DSLOGO}`, `${URLS.UI}${FILE_NAMES.DSLOGO}`],
  //LEVELS
  [`${FILE_NAMES.LEVEL_LAVONEY}`, `${URLS.LEVELS}${FILE_NAMES.LEVEL_LAVONEY}`],

  //ICONS
  [`${FILE_NAMES.ICONS_LIVES}`, `${URLS.ICONS}${FILE_NAMES.ICONS_LIVES}`], 
  [`${FILE_NAMES.ICONS_COINS}`, `${URLS.ICONS}${FILE_NAMES.ICONS_COINS}`], 
  [`${FILE_NAMES.ICONS_EXP}`, `${URLS.ICONS}${FILE_NAMES.ICONS_EXP}`], 
  [`${FILE_NAMES.ICONS_MANA}`, `${URLS.ICONS}${FILE_NAMES.ICONS_MANA}`], 
  [`${FILE_NAMES.ICONS_WAVES}`, `${URLS.ICONS}${FILE_NAMES.ICONS_WAVES}`], 
  [`${FILE_NAMES.ICONS_PAUSE}`, `${URLS.ICONS}${FILE_NAMES.ICONS_PAUSE}`], 
  [`${FILE_NAMES.ICONS_AUDIO}`, `${URLS.ICONS}${FILE_NAMES.ICONS_AUDIO}`], 
  [`${FILE_NAMES.ICONS_SETTINGS}`, `${URLS.ICONS}${FILE_NAMES.ICONS_SETTINGS}`], 
  [`${FILE_NAMES.ICONS_TIMER}`, `${URLS.ICONS}${FILE_NAMES.ICONS_TIMER}`], 

  //MUSIC 
  [`${FILE_NAMES.MUSIC_MAIN_MENU}`, `${URLS.MUSIC}${FILE_NAMES.MUSIC_MAIN_MENU}`],

  //SOUNDFX

  //ENEMIES
  [`${FILE_NAMES.ZOMBIE_CHEEKS_DIE}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_CHEEKS_DIE}`],
  [`${FILE_NAMES.ZOMBIE_CHEEKS_IDLE}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_CHEEKS_IDLE}`],
  [`${FILE_NAMES.ZOMBIE_CHEEKS_ATTACK}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_CHEEKS_ATTACK}`],
  [`${FILE_NAMES.ZOMBIE_CHEEKS_WALK}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_CHEEKS_WALK}`],
  
  [`${FILE_NAMES.ZOMBIE_DARK_CHEEKS_DIE}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_DARK_CHEEKS_DIE}`],
  [`${FILE_NAMES.ZOMBIE_DARK_CHEEKS_IDLE}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_DARK_CHEEKS_IDLE}`],
  [`${FILE_NAMES.ZOMBIE_DARK_CHEEKS_ATTACK}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_DARK_CHEEKS_ATTACK}`],
  [`${FILE_NAMES.ZOMBIE_DARK_CHEEKS_WALK}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_DARK_CHEEKS_WALK}`],
  
  [`${FILE_NAMES.ZOMBIE_CRAWLER_ATTACK}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_CRAWLER_ATTACK}`],
  [`${FILE_NAMES.ZOMBIE_CRAWLER_DIE}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_CRAWLER_DIE}`],
  [`${FILE_NAMES.ZOMBIE_CRAWLER_IDLE}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_CRAWLER_IDLE}`],
  [`${FILE_NAMES.ZOMBIE_CRAWLER_WALK}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_CRAWLER_WALK}`],

  [`${FILE_NAMES.ZOMBIE_DARK_CRAWLER_ATTACK}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_DARK_CRAWLER_ATTACK}`],
  [`${FILE_NAMES.ZOMBIE_DARK_CRAWLER_DIE}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_DARK_CRAWLER_DIE}`],
  [`${FILE_NAMES.ZOMBIE_DARK_CRAWLER_IDLE}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_DARK_CRAWLER_IDLE}`],
  [`${FILE_NAMES.ZOMBIE_DARK_CRAWLER_WALK}`, `${URLS.ZOMBIES}${FILE_NAMES.ZOMBIE_DARK_CRAWLER_WALK}`],
  
  //TOWERS
  [`${FILE_NAMES.TOWER_EMPTY_SPOT}`, `${URLS.TOWERS}${FILE_NAMES.TOWER_EMPTY_SPOT}`],
  [`${FILE_NAMES.TOWER_AMETHYST_1}`, `${URLS.TOWERS}${FILE_NAMES.TOWER_AMETHYST_1}`],

  //PROJECTILES
  [`${FILE_NAMES.PROJECTILE_SAPPHIRE_1}`, `${URLS.PROJECTILES}${FILE_NAMES.PROJECTILE_SAPPHIRE_1}`],

  //EFFECTS
];
