import * as OBJECTS from "./objects.js";

const EFFECTS_URL = './images/effects/'; 
const ENEMIES_URL = './images/enemies/';
const PROJECTILES_URL = './images/projectiles/';
const TOWERS_URL = './images/towers/';
const ICONS_URL = './images/icons/';

export const URL_NUMBER = {
    ONE: ' (1)',
    TWO: ' (2)',
    THREE: ' (3)',
    FOUR: ' (4)',
    FIVE: ' (5)',
    SIX: ' (6)',
}

export const ASSET_TYPE = {
    IMAGE: 'image',
    SOUND: 'sound',
};

export const ASSET_TYPE_LOOKUP = {
    png: ASSET_TYPE.IMAGE,
    mp3: ASSET_TYPE.SOUND,
    ogg: ASSET_TYPE.SOUND,
}

export const ASSET_LIST = [
    ['menuLogo',    './images/logos/menuLogo.png'],
    ['hellwortica',  './images/levels/hellwortica/hellwortica.png'],
    ['towerSpot',   './images/levels/towerSpot.png'],
    ['bossWave',    './audio/bossWave.ogg'],
    ['menuMusic',   './audio/menuMusic.mp3'],
    ['blood',       `${EFFECTS_URL}blood_110x110.png`],
    ['blueExplosion',   `${EFFECTS_URL}blueExplosion_256x256.png`],
    ['sapphireProjectile',    `${PROJECTILES_URL}sapphireProjectile_50x25.png`],
    //GUI
    ['life',        `${ICONS_URL}life.png`],
    ['coin',        `${ICONS_URL}coin.png`],
    ['experience',  `${ICONS_URL}experience.png`],
    ['wave',        `${ICONS_URL}wave.png`],
    ['time',        `${ICONS_URL}time.png`],
    //ENEMIES
    [`${OBJECTS.COLOURS.AMETHYST}`, `${ENEMIES_URL}${OBJECTS.COLOURS.AMETHYST}.png`],
    [`${OBJECTS.COLOURS.CITRINE}`,  `${ENEMIES_URL}${OBJECTS.COLOURS.CITRINE}.png`],
    [`${OBJECTS.COLOURS.DIAMOND}`,  `${ENEMIES_URL}${OBJECTS.COLOURS.DIAMOND}.png`],
    [`${OBJECTS.COLOURS.EMERALD}`,  `${ENEMIES_URL}${OBJECTS.COLOURS.EMERALD}.png`],
    [`${OBJECTS.COLOURS.GOLD}`,     `${ENEMIES_URL}${OBJECTS.COLOURS.GOLD}.png`],
    [`${OBJECTS.COLOURS.OBSIDIAN}`, `${ENEMIES_URL}${OBJECTS.COLOURS.OBSIDIAN}.png`],
    [`${OBJECTS.COLOURS.OPAL}`,     `${ENEMIES_URL}${OBJECTS.COLOURS.OPAL}.png`],
    [`${OBJECTS.COLOURS.RUBY}`,     `${ENEMIES_URL}${OBJECTS.COLOURS.RUBY}.png`],
    [`${OBJECTS.COLOURS.SAPPHIRE}`, `${ENEMIES_URL}${OBJECTS.COLOURS.SAPPHIRE}.png`],
    [`${OBJECTS.COLOURS.SILVER}`,   `${ENEMIES_URL}${OBJECTS.COLOURS.SILVER}.png`],
    [`${OBJECTS.COLOURS.TOPAZ}`,    `${ENEMIES_URL}${OBJECTS.COLOURS.TOPAZ}.png`],
    [`${OBJECTS.COLOURS.URANIUM}`,  `${ENEMIES_URL}${OBJECTS.COLOURS.URANIUM}.png`],
    //TOWERS
    [`${OBJECTS.COLOURS.AMETHYST}${OBJECTS.TYPES.TOWER}1`, `${TOWERS_URL}${OBJECTS.COLOURS.AMETHYST}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`], 
    // [`${OBJECTS.COLOURS.CITRINE}${OBJECTS.TYPES.TOWER}1`,  `${TOWERS_URL}${OBJECTS.COLOURS.CITRINE}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    [`${OBJECTS.COLOURS.DIAMOND}${OBJECTS.TYPES.TOWER}1`,  `${TOWERS_URL}${OBJECTS.COLOURS.DIAMOND}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    [`${OBJECTS.COLOURS.EMERALD}${OBJECTS.TYPES.TOWER}1`,  `${TOWERS_URL}${OBJECTS.COLOURS.EMERALD}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    // [`${OBJECTS.COLOURS.GOLD}${OBJECTS.TYPES.TOWER}1`,     `${TOWERS_URL}${OBJECTS.COLOURS.GOLD}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    // [`${OBJECTS.COLOURS.OBSIDIAN}${OBJECTS.TYPES.TOWER}1`, `${TOWERS_URL}${OBJECTS.COLOURS.OBSIDIAN}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    // [`${OBJECTS.COLOURS.OPAL}${OBJECTS.TYPES.TOWER}1`,     `${TOWERS_URL}${OBJECTS.COLOURS.OPAL}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    [`${OBJECTS.COLOURS.RUBY}${OBJECTS.TYPES.TOWER}1`,     `${TOWERS_URL}${OBJECTS.COLOURS.RUBY}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    [`${OBJECTS.COLOURS.SAPPHIRE}${OBJECTS.TYPES.TOWER}1`, `${TOWERS_URL}${OBJECTS.COLOURS.SAPPHIRE}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    // [`${OBJECTS.COLOURS.SILVER}${OBJECTS.TYPES.TOWER}1`,   `${TOWERS_URL}${OBJECTS.COLOURS.SILVER}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    [`${OBJECTS.COLOURS.TOPAZ}${OBJECTS.TYPES.TOWER}1`,    `${TOWERS_URL}${OBJECTS.COLOURS.TOPAZ}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],
    // [`${OBJECTS.COLOURS.URANIUM}${OBJECTS.TYPES.TOWER}1`,  `${TOWERS_URL}${OBJECTS.COLOURS.URANIUM}${OBJECTS.TYPES.TOWER}${URL_NUMBER.ONE}.png`],

    [`${OBJECTS.COLOURS.AMETHYST}${OBJECTS.TYPES.TOWER}2`, `${TOWERS_URL}${OBJECTS.COLOURS.AMETHYST}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`], 
    // [`${OBJECTS.COLOURS.CITRINE}${OBJECTS.TYPES.TOWER}2`,  `${TOWERS_URL}${OBJECTS.COLOURS.CITRINE}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    [`${OBJECTS.COLOURS.DIAMOND}${OBJECTS.TYPES.TOWER}2`,  `${TOWERS_URL}${OBJECTS.COLOURS.DIAMOND}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    [`${OBJECTS.COLOURS.EMERALD}${OBJECTS.TYPES.TOWER}2`,  `${TOWERS_URL}${OBJECTS.COLOURS.EMERALD}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    // [`${OBJECTS.COLOURS.GOLD}${OBJECTS.TYPES.TOWER}2`,     `${TOWERS_URL}${OBJECTS.COLOURS.GOLD}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    // [`${OBJECTS.COLOURS.OBSIDIAN}${OBJECTS.TYPES.TOWER}2`, `${TOWERS_URL}${OBJECTS.COLOURS.OBSIDIAN}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    // [`${OBJECTS.COLOURS.OPAL}${OBJECTS.TYPES.TOWER}2`,     `${TOWERS_URL}${OBJECTS.COLOURS.OPAL}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    [`${OBJECTS.COLOURS.RUBY}${OBJECTS.TYPES.TOWER}2`,     `${TOWERS_URL}${OBJECTS.COLOURS.RUBY}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    [`${OBJECTS.COLOURS.SAPPHIRE}${OBJECTS.TYPES.TOWER}2`, `${TOWERS_URL}${OBJECTS.COLOURS.SAPPHIRE}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    // [`${OBJECTS.COLOURS.SILVER}${OBJECTS.TYPES.TOWER}2`,   `${TOWERS_URL}${OBJECTS.COLOURS.SILVER}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    [`${OBJECTS.COLOURS.TOPAZ}${OBJECTS.TYPES.TOWER}2`,    `${TOWERS_URL}${OBJECTS.COLOURS.TOPAZ}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],
    // [`${OBJECTS.COLOURS.URANIUM}${OBJECTS.TYPES.TOWER}2`,  `${TOWERS_URL}${OBJECTS.COLOURS.URANIUM}${OBJECTS.TYPES.TOWER}${URL_NUMBER.TWO}.png`],

    [`${OBJECTS.COLOURS.AMETHYST}${OBJECTS.TYPES.TOWER}3`, `${TOWERS_URL}${OBJECTS.COLOURS.AMETHYST}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`], 
    // [`${OBJECTS.COLOURS.CITRINE}${OBJECTS.TYPES.TOWER}3`,  `${TOWERS_URL}${OBJECTS.COLOURS.CITRINE}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    [`${OBJECTS.COLOURS.DIAMOND}${OBJECTS.TYPES.TOWER}3`,  `${TOWERS_URL}${OBJECTS.COLOURS.DIAMOND}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    [`${OBJECTS.COLOURS.EMERALD}${OBJECTS.TYPES.TOWER}3`,  `${TOWERS_URL}${OBJECTS.COLOURS.EMERALD}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    // [`${OBJECTS.COLOURS.GOLD}${OBJECTS.TYPES.TOWER}3`,     `${TOWERS_URL}${OBJECTS.COLOURS.GOLD}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    // [`${OBJECTS.COLOURS.OBSIDIAN}${OBJECTS.TYPES.TOWER}3`, `${TOWERS_URL}${OBJECTS.COLOURS.OBSIDIAN}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    // [`${OBJECTS.COLOURS.OPAL}${OBJECTS.TYPES.TOWER}3`,     `${TOWERS_URL}${OBJECTS.COLOURS.OPAL}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    [`${OBJECTS.COLOURS.RUBY}${OBJECTS.TYPES.TOWER}3`,     `${TOWERS_URL}${OBJECTS.COLOURS.RUBY}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    [`${OBJECTS.COLOURS.SAPPHIRE}${OBJECTS.TYPES.TOWER}3`, `${TOWERS_URL}${OBJECTS.COLOURS.SAPPHIRE}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    // [`${OBJECTS.COLOURS.SILVER}${OBJECTS.TYPES.TOWER}3`,   `${TOWERS_URL}${OBJECTS.COLOURS.SILVER}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    [`${OBJECTS.COLOURS.TOPAZ}${OBJECTS.TYPES.TOWER}3`,    `${TOWERS_URL}${OBJECTS.COLOURS.TOPAZ}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    // [`${OBJECTS.COLOURS.URANIUM}${OBJECTS.TYPES.TOWER}3`,  `${TOWERS_URL}${OBJECTS.COLOURS.URANIUM}${OBJECTS.TYPES.TOWER}${URL_NUMBER.THREE}.png`],
    
] 